version: '3.7'
services:
  tuya:
    container_name: tuya-convert
    image: scyto/tuya-convert:latest
    privileged: true
    network_mode: "host"
    tty: true
    stop_signal: SIGINT
    stop_grace_period: 2s
    environment:
      - WLAN=wlan0
      - AP=vtrust-flash
      - GATEWAY=10.42.42.1
    volumes:
      - ./data/backups:/usr/bin/tuya-convert/backups
