name: build-and-push-docker-image
 
on:
  push:
    branches: [ master ]
    paths-ignore: #this ensures auto rebuilds don't occure when README.md is updated or the seperate workflow for updating descriptions and readme is modifies
        - 'README.md'
        - '.github/workflows/update-dockerhub-metadata.yml'
  pull_request:
    branches: [ master ]
    paths-ignore: #this ensures auto rebuilds don't occure when README.md is updated or the seperate workflow for updating descriptions and readme is modifies
        - 'README.md'
        - '.github/workflows/update-dockerhub-metadata.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #set these secrets in your guthub account
          password: ${{ secrets.DOCKERHUB_TOKEN }} #set these secrets in your github account

      - name: Available_platforms 
        run: echo ${{ steps.buildx.outputs.platforms }} #this is for logging

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }} #this is for logging

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: scyto/tuya-convert:latest #set to the dockerhub repo this will be pushed to

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} #this is for logging.
        
